BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
    XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXX XXXXXXXX XXXXX
                XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    
                XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
    
        XXXXXX
    XXXXXXX

BBBBBBBB BBBBBBB
