BBBB BBBBBBBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX      
      XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXX

    XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX    
      XXXXXX XXXXXXBBB BBBBBBBBXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXX XXXXXXXXX
    XXXXX
	
  XXXXXX
XXXXXX

XXXX XXXXXXXXXX XXXXXXXX
  XXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXX XXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXXXX  
XXXXXX

XXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX
      XXX XXXXXXXBB BBBB BB BBBBBBXXXXXXBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXBB BBBB BB BBBBBBBBBBBBXXXXXXBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXX XXXXXXXBB BBBB BB BBBBBBBBBBXXXXXXBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXX XXXXXXXBB BBBB BB BBBBBBBBBXXXXXXBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
  BBBBB BBBBBBB
  BBBBBBBB

  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX
  XXXXXXX XX XXXXXX
XXXXXX

XXXXXXX
XXXXXXX
