BBBB BBBBBBBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXXXXXXXX XXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX XXXXXXBBB BBBBBBBBXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXX XXXXXXXXX
        XXXXX
	
    XXXXXX
XXXXXX

XXXX XXXXXXXXXX XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXX XXX XXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXX  XXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX X XXXXXXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX
            XXX XXXXXXXBB BBBB BB BBBBBBXXXXXXBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXBB BBBB BB BBBBBBBBBBBBXXXXXXBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXX XXXXXXXBB BBBB BB BBBBBBBBBBBBXXXXXXBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXX XXXXXXXBB BBBB BB BBBBBBBBBBBXXXXXXBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXX XXXXXXXBB BBBB BB BBBBBBBBBBBXXXXXXBBBBBXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

        XXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
        BBBBB BBBBBBB
    

        BBBBBBBB
    XXXXXXXXXXXXX XX XXXXXXXXXX


XXXXXXXXXX XXX XX XXXXXXX XXXXX XXX

XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX
    XXXXXXX XX XXXXXX
XXXXXX

XXXXXXX
XXXXXXX
