# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20170411_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectorUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='detector/')),
                ('clientid', models.CharField(default='null', max_length=50)),
                ('m', models.CharField(default='null', max_length=150)),
                ('mdash', models.CharField(default='null', max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
