# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_detectorupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectorupload',
            name='status',
            field=models.CharField(default='No', max_length=20),
        ),
    ]
