# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20170423_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectorupload',
            name='status',
            field=models.CharField(default='Not Viewed', max_length=20),
        ),
    ]
