# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20170423_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
